In [27]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

plt.rc('font', family='AppleGothic')

In [61]:
df = pd.read_csv('./makeDataset/dataset/processedData/31_0.8.csv')
df
data = df
use_cols = ['총인구수(명)', '유치원 수', '출생건수', '사망건수', '혼인건수', '이혼건수', '학령인구(명)']

In [62]:
df = df.drop(['Unnamed: 0'], axis=1)
df.head()

행정구역(시도) 행정구역(시군구)    연도        총인구수(명)      유치원 수     초등학교 수         출생건수  \
0    서울특별시       종로구  2010  212578.440599  21.442605  16.129821  1588.378087   
1    서울특별시        중구  2010  183843.149349  18.423046  14.631716  1644.967317   
2    서울특별시       용산구  2010  275855.647548  23.476621  17.187879  2597.790536   
3    서울특별시       성동구  2010  326063.730303  32.928679  21.056024  3022.010963   
4    서울특별시       광진구  2010  385969.004529  42.114773  23.076967  3492.096293   

          사망건수         혼인건수        이혼건수  학령인구(명)   총인구수-학령인구(명)       행정구역  
0   985.320450  1324.571165  485.090779    29164  175066.084329  서울특별시 종로구  
1   844.969726  1359.302603  471.841074    19628  153625.741021   서울특별시 중구  
2  1179.482840  1973.791681  596.083716    37318  230932.033815  서울특별시 용산구  
3  1296.846556  2368.527386  712.493262    51562  270121.710326  서울특별시 성동구  
4  1356.494357  2715.029681  831.841669    67422  315593.048191  서울특별시 광진구

In [63]:
df['행정구역'].value_counts()

행정구역
서울특별시 종로구       13
전라북도 장수군        13
충청남도 예산군        13
충청남도 태안군        13
전라북도 전주시        13
                ..
경기도 동두천시        13
경기도 안산시         13
경기도 고양시         13
경기도 과천시         13
제주특별자치도 서귀포시    13
Name: count, Length: 223, dtype: int64

In [64]:
# 데이터 전처리
scaler = MinMaxScaler()
df[use_cols] = scaler.fit_transform(df[use_cols])

/opt/homebrew/Caskroom/miniforge/base/envs/dataScience/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/opt/homebrew/Caskroom/miniforge/base/envs/dataScience/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/opt/homebrew/Caskroom/miniforge/base/envs/dataScience/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/opt/homebrew/Caskroom/miniforge/base/envs/dataScience/lib/python3.11/site-packages/skl

In [65]:
# 연도가 2013부터 2020까지인 데이터 추출
filtered_df = df[(df['연도'] >= 2010) & (df['연도'] <= 2021)]

# 결과 출력
print(filtered_df)

     행정구역(시도) 행정구역(시군구)    연도   총인구수(명)     유치원 수     초등학교 수      출생건수  \
0       서울특별시       종로구  2010  0.197333  0.095390  16.129821  0.150142   
1       서울특별시        중구  2010  0.169498  0.076738  14.631716  0.155559   
2       서울특별시       용산구  2010  0.258629  0.107954  17.187879  0.246773   
3       서울특별시       성동구  2010  0.307265  0.166340  21.056024  0.287384   
4       서울특별시       광진구  2010  0.365295  0.223084  23.076967  0.332386   
...       ...       ...   ...       ...       ...        ...       ...   
2671     경상남도       함양군  2021  0.029430  0.039872  13.433378  0.008448   
2672     경상남도       거창군  2021  0.045402  0.055905  16.063477  0.015353   
2673     경상남도       합천군  2021  0.037443  0.057750  16.678551  0.011316   
2674  제주특별자치도       제주시  2021  0.409119  0.403981  63.400000  0.235459   
2675  제주특별자치도      서귀포시  2021  0.229272  0.281675  49.600000  0.117595   

          사망건수      혼인건수      이혼건수   학령인구(명)   총인구수-학령인구(명)          행정구역  
0     0.163830  0.181343  0.216548 

In [66]:
filtered_df

행정구역(시도) 행정구역(시군구)    연도   총인구수(명)     유치원 수     초등학교 수      출생건수  \
0       서울특별시       종로구  2010  0.197333  0.095390  16.129821  0.150142   
1       서울특별시        중구  2010  0.169498  0.076738  14.631716  0.155559   
2       서울특별시       용산구  2010  0.258629  0.107954  17.187879  0.246773   
3       서울특별시       성동구  2010  0.307265  0.166340  21.056024  0.287384   
4       서울특별시       광진구  2010  0.365295  0.223084  23.076967  0.332386   
...       ...       ...   ...       ...       ...        ...       ...   
2671     경상남도       함양군  2021  0.029430  0.039872  13.433378  0.008448   
2672     경상남도       거창군  2021  0.045402  0.055905  16.063477  0.015353   
2673     경상남도       합천군  2021  0.037443  0.057750  16.678551  0.011316   
2674  제주특별자치도       제주시  2021  0.409119  0.403981  63.400000  0.235459   
2675  제주특별자치도      서귀포시  2021  0.229272  0.281675  49.600000  0.117595   

          사망건수      혼인건수      이혼건수   학령인구(명)   총인구수-학령인구(명)          행정구역  
0     0.163830  0.181343  0.216548  0.116964  175066.084329     서울특별시 종로구  
1     0.139034  0.186212  0.210392  0.077754  153625.741021      서울특별시 중구  
2     0.198132  0.272356  0.268116  0.150492  230932.033815     서울특별시 용산구  
3     0.218867  0.327693  0.322200  0.209060  270121.710326     서울특별시 성동구  
4     0.229405  0.376269  0.377650  0.274273  315593.048191     서울특별시 광진구  
...        ...       ...       ...       ...            ...           ...  
2671  0.093742  0.006023  0.026379  0.015144   34696.206699      경상남도 함양군  
2672  0.108500  0.013072  0.043528  0.034021   47862.492130      경상남도 거창군  
2673  0.120529  0.009258  0.032690  0.011908   42879.407008      경상남도 합천군  
2674  0.445208  0.232852  0.427065  0.352866  356271.400000   제주특별자치도 제주시  
2675  0.281435  0.131496  0.247541  0.114423  205405.600000  제주특별자치도 서귀포시  

[2676 rows x 13 columns]

In [68]:
# 시퀀스 데이터 생성
def create_sequence_data(data, sequence_length):
    sequences = []
    for region in data['행정구역'].unique().tolist():
        temp_df = data[data['행정구역'] == region]
        if len(temp_df) < sequence_length:
            continue

        temp_df = temp_df[use_cols]
        for i in range(len(temp_df) - sequence_length):
            seq = temp_df[i:i+sequence_length+1]
            sequences.append(seq)
    return np.array(sequences)

In [69]:
sequence_length = 3  # 시퀀스 길이
sequences = create_sequence_data(filtered_df, sequence_length)

In [70]:
sequences.shape

(2007, 4, 7)

In [71]:
# 데이터셋 분리
X = sequences[:, :-1]
y = sequences[:, -1][:, -1]

In [72]:
# 훈련/검증 데이터셋 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

In [73]:
def invTransform(scaler, data, colName, colNames):
    dummy = pd.DataFrame(np.zeros((len(data), len(colNames))), columns=colNames)
    dummy[colName] = data
    dummy = pd.DataFrame(scaler.inverse_transform(dummy), columns=colNames)
    return dummy[colName].values

In [74]:
# MAPE 계산 함수
def calculate_mape(y_true, y_pred):
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

In [75]:
prediction_df = df[df['연도'].isin([i for i in range(2019, 2023)])]

In [76]:
prediction_df

행정구역(시도) 행정구역(시군구)    연도   총인구수(명)     유치원 수     초등학교 수      출생건수  \
2007    서울특별시       종로구  2019  0.180944  0.096013  15.624091  0.090377   
2008    서울특별시        중구  2019  0.162695  0.082192  14.909673  0.099192   
2009    서울특별시       용산구  2019  0.245324  0.080499  17.542308  0.142511   
2010    서울특별시       성동구  2019  0.299138  0.161376  22.134323  0.207204   
2011    서울특별시       광진구  2019  0.345574  0.180692  23.486902  0.195017   
...       ...       ...   ...       ...       ...        ...       ...   
2894     경상남도       함양군  2022  0.028842  0.039699  13.433378  0.006182   
2895     경상남도       거창군  2022  0.044776  0.055680  16.063477  0.012975   
2896     경상남도       합천군  2022  0.036731  0.057304  16.678551  0.011296   
2897  제주특별자치도       제주시  2022  0.409560  0.384214  64.200000  0.225867   
2898  제주특별자치도      서귀포시  2022  0.230187  0.276733  49.800000  0.114838   

          사망건수      혼인건수      이혼건수   학령인구(명)   총인구수-학령인구(명)          행정구역  
2007  0.171169  0.112533  0.151951  0.076697  169465.363600     서울특별시 종로구  
2008  0.145327  0.127460  0.141452  0.049806  155565.278298      서울특별시 중구  
2009  0.208910  0.195805  0.197073  0.108666  228872.646025     서울특별시 용산구  
2010  0.246095  0.243891  0.254050  0.149069  276971.482367     서울특별시 성동구  
2011  0.250800  0.264893  0.282864  0.185660  316310.353186     서울특별시 광진구  
...        ...       ...       ...       ...            ...           ...  
2894  0.108013  0.008640  0.020021  0.014050   34356.247460      경상남도 함양군  
2895  0.125601  0.016003  0.031581  0.032195   47610.710977      경상남도 거창군  
2896  0.143985  0.011113  0.028399  0.010966   42373.986459      경상남도 합천군  
2897  0.507361  0.242946  0.443698  0.343861  358553.600000   제주특별자치도 제주시  
2898  0.321221  0.129393  0.265289  0.112893  207085.400000  제주특별자치도 서귀포시  

[892 rows x 13 columns]

In [77]:
predict_sequences = create_sequence_data(prediction_df, sequence_length)

In [78]:
predict_sequences

array([[[0.18094357, 0.09601254, 0.090377  , ..., 0.11253341,
         0.15195109, 0.07669724],
        [0.17927245, 0.09456216, 0.07524318, ..., 0.10556596,
         0.15334   , 0.07237575],
        [0.17486437, 0.08926164, 0.07382473, ..., 0.08950867,
         0.1254377 , 0.06836676],
        [0.1718843 , 0.08904231, 0.06731446, ..., 0.0893154 ,
         0.1196204 , 0.0646867 ]],

       [[0.1626953 , 0.08219157, 0.09919176, ..., 0.12745986,
         0.14145235, 0.04980613],
        [0.16172052, 0.08071151, 0.08777363, ..., 0.11561669,
         0.15027197, 0.04750353],
        [0.1587832 , 0.08023942, 0.08169532, ..., 0.10205104,
         0.1361821 , 0.0447733 ],
        [0.15673189, 0.07995573, 0.07688445, ..., 0.09231204,
         0.11864769, 0.04228977]],

       [[0.24532372, 0.08049875, 0.14251123, ..., 0.19580464,
         0.19707325, 0.10866642],
        [0.24621503, 0.07902295, 0.12744748, ..., 0.17726575,
         0.19027533, 0.1055538 ],
        [0.24003263, 0.07861535, 0.1

In [79]:
# 데이터셋 분리
predict_X = predict_sequences[:, :-1]
predict_y = predict_sequences[:, -1][:, -1]

In [80]:
predict_X

array([[[0.18094357, 0.09601254, 0.090377  , ..., 0.11253341,
         0.15195109, 0.07669724],
        [0.17927245, 0.09456216, 0.07524318, ..., 0.10556596,
         0.15334   , 0.07237575],
        [0.17486437, 0.08926164, 0.07382473, ..., 0.08950867,
         0.1254377 , 0.06836676]],

       [[0.1626953 , 0.08219157, 0.09919176, ..., 0.12745986,
         0.14145235, 0.04980613],
        [0.16172052, 0.08071151, 0.08777363, ..., 0.11561669,
         0.15027197, 0.04750353],
        [0.1587832 , 0.08023942, 0.08169532, ..., 0.10205104,
         0.1361821 , 0.0447733 ]],

       [[0.24532372, 0.08049875, 0.14251123, ..., 0.19580464,
         0.19707325, 0.10866642],
        [0.24621503, 0.07902295, 0.12744748, ..., 0.17726575,
         0.19027533, 0.1055538 ],
        [0.24003263, 0.07861535, 0.13037635, ..., 0.15031407,
         0.18335441, 0.09938611]],

       ...,

       [[0.03935444, 0.05815941, 0.01706188, ..., 0.01735473,
         0.03987933, 0.01470377],
        [0.03834318, 

In [81]:
predict_y

array([0.0646867 , 0.04228977, 0.0943615 , 0.12830434, 0.15947583,
       0.15883439, 0.16461557, 0.24233665, 0.12972702, 0.15108777,
       0.30837202, 0.23509578, 0.15474316, 0.18207835, 0.29678088,
       0.28152613, 0.18906017, 0.08767162, 0.16144538, 0.18147802,
       0.18175351, 0.27697027, 0.3614059 , 0.38045172, 0.25540803,
       0.009416  , 0.04527905, 0.028873  , 0.04217464, 0.16244865,
       0.1642414 , 0.14601382, 0.14327948, 0.23125537, 0.15606715,
       0.10859652, 0.09932032, 0.10466976, 0.07429596, 0.09146269,
       0.12256839, 0.03697734, 0.06128214, 0.2704243 , 0.29997574,
       0.3362623 , 0.1716344 , 0.08852687, 0.02713782, 0.28344634,
       0.30803074, 0.2613249 , 0.15410583, 0.39705514, 0.0252135 ,
       0.00473267, 0.05073539, 0.18616547, 0.14384691, 0.26654688,
       0.32210129, 0.12451738, 0.12817687, 0.3070398 , 0.24994757,
       0.09525787, 0.12212843, 0.18612435, 0.10066076, 0.16010904,
       0.13690209, 0.75345699, 0.54618158, 0.2699021 , 0.32085

In [82]:
from tensorflow.keras.models import load_model

# Load the best model
best_model = load_model('best_model.h5')

In [84]:
# 예측
predicted_data = best_model.predict(predict_X)

# 예측 결과 역전환
#predicted_data = scaler.inverse_transform(predicted_data)
predicted_data = invTransform(scaler, predicted_data, '학령인구(명)', use_cols).reshape(-1, 1)
predicted_data = predicted_data.round()
#y_true = scaler.inverse_transform(y_test.reshape(-1, 1))
y_true = invTransform(scaler, predict_y, '학령인구(명)', use_cols).reshape(-1, 1)

# 결과 시각화
plt.plot(range(len(y_true)), y_true, label='True')
plt.plot(range(len(predicted_data)), predicted_data, label='Predicted', linestyle='--')
plt.xlabel('Test Case')
plt.ylabel('School_Age_Population')
plt.legend()
plt.show()

# 모델 평가
mse = mean_squared_error(y_true, predicted_data)
print(f'Mean Squared Error: {mse:.2f}')

# MAPE 계산 함수
def calculate_mape(y_true, y_pred):
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

# MAPE 계산
mape = calculate_mape(y_true, predicted_data)
print(f'Mean Absolute Percentage Error (MAPE): {mape:.2f}%')

ValueError: in user code:

    File "/opt/homebrew/Caskroom/miniforge/base/envs/dataScience/lib/python3.11/site-packages/keras/src/engine/training.py", line 2440, in predict_function  *
        return step_function(self, iterator)
    File "/opt/homebrew/Caskroom/miniforge/base/envs/dataScience/lib/python3.11/site-packages/keras/src/engine/training.py", line 2425, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/opt/homebrew/Caskroom/miniforge/base/envs/dataScience/lib/python3.11/site-packages/keras/src/engine/training.py", line 2413, in run_step  **
        outputs = model.predict_step(data)
    File "/opt/homebrew/Caskroom/miniforge/base/envs/dataScience/lib/python3.11/site-packages/keras/src/engine/training.py", line 2381, in predict_step
        return self(x, training=False)
    File "/opt/homebrew/Caskroom/miniforge/base/envs/dataScience/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/opt/homebrew/Caskroom/miniforge/base/envs/dataScience/lib/python3.11/site-packages/keras/src/engine/input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential_5" is incompatible with the layer: expected shape=(None, 3, 8), found shape=(None, 3, 7)
